### ISSUE TITLE
No installation on 9.1.3 nand 9.1.2

### ISSUE THREAD

**Issue by S1L3NC3** [FutureProcessing/glpi-fpsoftware#10]
Hi there:
I'm trying to install this plugin in different version (9.1.2 and 9.1.3) but the normal method for plugins is not valid (installing on /glpi/plugins/ )
Could you please give us notes about how to install in these versions? thanks in advance.

**Comment by prybak** [comment]
What's the issue? Are you able to see/install plugin from Setup/Plugins?
Did you set appropriate rights to the plugin folder in GLPI /plugins folder?

**Comment by S1L3NC3** [comment]
Hi prybak, i am not able to see this plugin from plugins. I checked the rights and it is seems to be correct. I've been tried to install it in the 3 last glpi version and i cannot find the error. Thanks in advance

**Comment by prybak** [comment]
That's strange, we have deployed it few days ago at 9.2.1 ;). 
Could you please give me some screen of what you have in plugins (how in general the folder structure looks like) and rights that were applied to the folder?

**Comment by S1L3NC3** [comment]
Hi there:
Many thanks!

Folder:
 4 drwxr-xr-x.  4 apache apache  4096 may 15  2017 fpsoft

Same rights for other plugin available in glpi:
 4 drwxr-xr-x.  7 apache apache  4096 dic  2  2016 addressing

Folder plugin has:
 4 drwxr-xr-x.  7 apache apache  4096 nov  3 18:39 plugins

In GLPI plugin interface it doesn't appear. 

Thanks in advance,
Regards!

**Comment by DGermany** [comment]
I had the same problem today. fixed it: 

You have to rename the unzipped package, that there is no more "-" in it. 

Old name : "glpi-fpsoftware-1.2" -> does not work.
New name: "fpsoftware" -> work :) 


Regards!

**Comment by S1L3NC3** [comment]
Many thx DGermany! I forgot to read this issue since my last comment; I just tried it and it works! Strange behavior for this, anyway it was very helpful.

Best Regards!

**Comment by prybak** [comment]
Using appropriate folder name solved the issue :).
