### ISSUE TITLE
Upgrade to 9.5

### ISSUE THREAD

**Issue by alaborda** [FutureProcessing/glpi-fpsoftware#13]
Hello:

  Any plan to upgrade plugin to GLPI 9.5.x?

Thank you very much.

**Comment by lFoxMulder** [comment]
Hi @alaborda,

not a real upgrade, but it shoud do the trick. Please change the following rows:

setup.php
row 48
`'version' => '1.5.0',`

row 67+68
`if (version_compare(GLPI_VERSION, '0.84', 'lt') || version_compare(GLPI_VERSION, '9.6', 'gt')) {
echo "This plugin requires GLPI >= 0.84 and GLPI <= 9.6";`

/inc/common.class.php
row 256
`if ($data = $DB->fetchassoc($result)) {`

row 323
`} while ($data=$DB->fetchassoc($result));`

/inc/userdetails.class.php
row 66
`while ($data = $DB->fetchassoc($result)) {`

/inc/userslicenses.class.php
row 114
`$row = $DB->fetchassoc($result);`

row 180
`while ($data = $DB->fetchassoc($queryResult)) {`

Now just install it the usual way.

**Comment by FPAdministrator** [comment]
This is solve by latest commits/releases.
