### ISSUE TITLE
not possible tto isntall

### ISSUE THREAD

**Issue by magheinz** [FutureProcessing/glpi-fpsoftware#2]
i cant't see this plugins inside of glpi.

**Comment by FPAdministrator** [comment]
Did you copy it to plugins folder and grant all necessary rights (same as for your GLPI instance)?

**Comment by FPAdministrator** [comment]
Closing as there was no reply.

**Comment by magaiverpr** [comment]
Just an information:

I had the same problem. To fix this I had to rename the folder to "fpsoftware". The original that was in the zip was "glpi-fpsoftware-1.2".
