### ISSUE TITLE
Plugins active but no licenses assign to users

### ISSUE THREAD

**Issue by boucchar** [FutureProcessing/glpi-fpsoftware#3]
![capture](https://cloud.githubusercontent.com/assets/10400225/10950875/241b0260-8308-11e5-8386-b72d1c2f7730.PNG)

This situation is for all users in entire glpi.

Note that i use fusioninventory to scan the software

**Comment by Phorms** [comment]
You have to open the "Licences" Tab in "Software", open a single License. Then you find the tab "User" and you can add the user to the license. If you now open the user menu you will see the licenses.

**Comment by prybak** [comment]
I guess that this issue has been solved ;).
