### ISSUE TITLE
Use Peripheral instead users

### ISSUE THREAD

**Issue by juanbreizh** [FutureProcessing/glpi-fpsoftware#7]
Hello,
i've tested your great plugin, and i tried (without success) modifying it to assign a software licence to a peripheral (in my case  : usb dongles) instead of users.

Can you help me doing this ?

Thanks for your help,
Juan

**Comment by prybak** [comment]
Is this still valid? 
Well, what do you mean by peripheral? Some item in Devices section? Or do you want to give it completely new functionality?

**Comment by prybak** [comment]
No action here.
